In [28]:
from constants import PROCESSED_DIR, RAW_DATASET_PATH, PROCESSED_DATASET
import dataset_utils as du
import pandas as pd
import numpy as np
from os import path

In [25]:
# Uncomment the following line to rerun pre-processing and tokenization
#prepare_and_save(RAW_DATASET_PATH, path.join(PROCESSED_DIR, PROCESSED_DATASET))

In [27]:
data = pd.read_pickle(path.join(PROCESSED_DIR, PROCESSED_DATASET))

interest = du.get_interest_dataset(data)
comprehension = du.get_comprehension_dataset(data)
comprehension = du.get_balanced_dataset(comprehension, 'comprehension_binary', random_state=1)
comprehension = comprehension.sample(frac=1, random_state=1) #Shuffle the dataset
features = du.get_features(comprehension)
labels = du.get_labels(comprehension, 'comprehension_binary')
folds = du.kfold_split(features, labels, num_folds=8)

/home/ubuntu/Question-Classifier/dataset_utils.py:80: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  interest['interest_binary'] = (interest['interest'] > 3).astype(int)
/home/ubuntu/Question-Classifier/dataset_utils.py:90: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comprehension['comprehension_binary'] = (comprehension['comprehension'] > 3).astype(int)


In [34]:
features = du.get_features(comprehension)
features

[array([[    5,     5,     5, ...,    82,     4,     3],
        [    5,     5,     5, ...,    82,     4,     3],
        [ 3619, 21559,  6234, ...,    82,     4,     3],
        ...,
        [   32,  3872,  4306, ...,    82,     4,     3],
        [    5,   247,   178, ...,    82,     4,     3],
        [    5,     5,     5, ...,    82,     4,     3]]),
 array([[3, 3, 3, ..., 1, 1, 2],
        [3, 3, 3, ..., 1, 1, 2],
        [0, 0, 0, ..., 1, 1, 2],
        ...,
        [0, 0, 0, ..., 1, 1, 2],
        [3, 0, 0, ..., 1, 1, 2],
        [3, 3, 3, ..., 1, 1, 2]]),
 array([[0, 0, 0, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [0, 1, 1, ..., 1, 1, 1],
        [0, 0, 0, ..., 1, 1, 1]]),
 array([[0.9491911 , 0.8865838 , 0.4116365 , ..., 0.93547505, 0.00432409,
         0.9028465 ],
        [0.93707097, 0.86747426, 0.169238  , ..., 0.9489544 , 0.00586284,
         0.8904263 ],
        [0.9366325 , 0.77